# Generated by Django 3.2.7 on 2022-05-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='table_name',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
