# Generated by Django 4.0.4 on 2022-06-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_file_month_file_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='month',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
