# Generated by Django 4.0.4 on 2022-06-11 07:38

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_currentemployees_resignedemployees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentemployees',
            name='Joining_Date',
            field=models.DateField(verbose_name=builtins.any),
        ),
        migrations.AlterField(
            model_name='resignedemployees',
            name='Joining_Date',
            field=models.DateField(verbose_name=builtins.any),
        ),
    ]
