# Generated by Django 4.0.4 on 2022-06-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_alter_currentemployees_joining_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentemployees',
            old_name='Full_Time_Contractual',
            new_name='Full_Time_or_Contractual',
        ),
        migrations.RenameField(
            model_name='currentemployees',
            old_name='Project_Function',
            new_name='Project_or_Function',
        ),
        migrations.RenameField(
            model_name='resignedemployees',
            old_name='Full_Time_Contractual',
            new_name='Full_Time_or_Contractual',
        ),
        migrations.RenameField(
            model_name='resignedemployees',
            old_name='Project_Function',
            new_name='Project_or_Function',
        ),
    ]
